### read
get http://localhost:3000/players

### read by id
get http://localhost:3000/players/apcj3hklbge9fnr

### delete
delete http://localhost:3000/players/apcj3hklbge9fnr

### post
post http://localhost:3000/players
Content-Type: application/json

{
    "name": "Armando",
    "qualification": 10,
    "position": "csatár",
    "club": "Újszásziak",
    "age": 20,
    "nationality": "magyar"
}

### put
put http://localhost:3000/players/apcj3hklbge9fnr
Content-Type: application/json

{
    "name": "<script>alert('betörtem')</script> heló",
    "qualification": 8,
    "position": "csatár",
    "club": "Újszásziak",
    "age": 25,
    "nationality": "magyar"
}
